t1 = (3, 12, 9)
print("t1:", t1)
print("Max. Wert:", max(t1))
print("Min. Wert:", min(t1))
print("Sum. Wert:", sum(t1))
print()

t2 = (1, 0, 13, 1, 2)
print("t2:", t2)
print("Max. Summe:", max(t1,t2))
print("Min. Summe:", min(t1,t2))
